<?php
/**
 * Its for Pos Counter module
 *
 * @package VitePos\Modules
 */

namespace vitepos\vitepos\modules;


use Automattic\WooCommerce\Utilities\NumberUtil;
use VitePos\Core\Vitepos_Module;
/**
 * Class POS_Counter
 */
class Pos_Plugins extends Vitepos_Module {

	/**
	 * The initialize is generated by appsbd
	 */
	public function initialize() {

	}
	/**
	 * The on init is generated by appsbd
	 */
	public function on_init() {
		parent::on_init();
	}

}
