<?php
/**
 * Its payment method base.
 *
 * @since: 21/09/2021
 * @author: Sarwar Hasan
 * @version 1.0.0
 * @package VitePos\Libs
 */

namespace vitepos_lite\libs;

use Matrix\Exception;
use VitePos\Modules\POS_Settings;

/**
 * Class Payment_Stripe_Method
 *
 * @package VitePos_Lite\Libs
 */
class Payment_Stripe_Terminal_Method extends Payment_Method_Base {
	/**
	 * Its property secret_key
	 *
	 * @var string
	 */
	protected $secret_key = '';

	/**
	 * The initialize is generated by appsbd
	 *
	 * @return mixed|void
	 */
	public function initialize() {
		$this->set_admin_name( 'stripe_terminal' );
		$this->title = 'Stripe Terminal';
		$this->icon  = 'vps vps vps-cc-stripe';
		$this->id    = 'R';
		$this->comp  = 'basic';
		$this->admin_data->is_pro = 'Y';
		$this->set_next_handler( 'STP', 'StripeTerminal' );
	}

	/**
	 * The load data is generated by appsbd
	 */
	public function load_data() {
	}

	/**
	 * The is enable is generated by appsbd
	 *
	 * @return bool
	 */
	public function is_enable() {
		return false;
	}


	/**
	 * The set admin settings is generated by appsbd
	 *
	 * @return mixed|void
	 */
	public function set_admin_settings() {
		$this->set_admin_title_desc(
			'Enable %{brand} Payment',
			'It will allow you to take payment using %{brand} Payment gateway, make sure you have added %{brand} api info in %{brand} settings tab.',
			array( 'brand' => 'Stripe Terminal' )
		);
	}
}
