<?php
/**
 * Insights Notice File
 *
 * @package dci
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( ! function_exists( 'vtp_dci_insights_popup_notice' ) ) {
	/**
	 * The dci insights popup notice is generated by appsbd
	 *
	 * @param mixed $data It is data param.
	 */
	function vtp_dci_insights_popup_notice( $data ) {

		?>
		<div class="apbd-dci-notice">
			<div class="apbd-dci-notice-wrapper">
				<div class="apbd-dci-header">
					<!-- <div class="apbd-dci-logo">
				<img src="plugins_url( 'assets/images/logo.png', __FILE__ );" alt="logo">
						</div> -->
					<h2 class="apbd-dci-title">
						<?php esc_html_e( 'Never miss an important update.', 'vitepos-lite' ); ?>
					</h2>
					<p class="apbd-dci-desc">
						<?php esc_html_e( 'Get notified when there are new updates available for your plugins and themes. In the current version of this message it is clear that you are being sent a confirmation email to confirm your opt-in.', 'vitepos-lite' ); ?>
					</p>
				</div>
				<div class="apbd-dci-actions">
					<?php
					$dci_name               = isset( $data['name'] ) ? $data['name'] : '';
					$dci_insights_date_name = isset( $data['date_name'] ) ? $data['date_name'] : '';
					$dci_allow_name         = isset( $data['allow_name'] ) ? $data['allow_name'] : '';
					$nonce                  = isset( $data['nonce'] ) ? $data['nonce'] : '';
					?>
					<form method="get" class="apbd-dci-notice-data">
						<input type="hidden" name="dci_name" value="<?php echo esc_html( $dci_name ); ?>">
						<input type="hidden" name="dci_date_name" value="<?php echo esc_html( $dci_insights_date_name ); ?>">
						<input type="hidden" name="dci_allow_name" value="<?php echo esc_html( $dci_allow_name ); ?>">
						<input type="hidden" name="nonce" value="<?php echo esc_html( $nonce ); ?>">

						<button id="dci_allow_yes" name="dci_allow_status" value="yes" type="button"
							class="apbd-dci-button-allow button button-primary">
							<?php esc_html_e( 'Allow & Continue', 'vitepos-lite' ); ?>
						</button>
						<button id="dci_allow_skip" name="dci_allow_status" value="skip" type="button"
							class="apbd-dci-button-skip button button-secondary">
							<?php esc_html_e( 'Skip', 'vitepos-lite' ); ?>
						</button>
					</form>
				</div>
				<div class="apbd-dci-permission">
					<p>
						<?php esc_html_e( 'Which permission are being granted?', 'vitepos-lite' ); ?>
					</p>
				</div>
				<div class="apbd-dci-data-list">
					<ul>
						<li>
							<div class="apbd-dci-permission-item">
								<div class="apbd-dci-icon">
									<span class="dashicons dashicons-admin-users"></span>
								</div>
								<div class="apbd-dci-desc">
									<h3>
										<?php esc_html_e( 'View Basic Profile Info.', 'vitepos-lite' ); ?>
									</h3>
									<p>
										<?php esc_html_e( 'Your WordPress user\'s first & last name, and email address.', 'vitepos-lite' ); ?>
									</p>
								</div>
							</div>
						</li>
						<li>
							<div class="apbd-dci-permission-item">
								<div class="apbd-dci-icon">
									<span class="dashicons dashicons-admin-links"></span>
								</div>
								<div class="apbd-dci-desc">
									<h3>
										<?php esc_html_e( 'View Basic Website Info.', 'vitepos-lite' ); ?>
									</h3>
									<p>
										<?php esc_html_e( 'Homepage URL & title, WP & PHP versions, and site language.', 'vitepos-lite' ); ?>
									</p>
								</div>
							</div>
						</li>
						<li>
							<div class="apbd-dci-permission-item">
								<div class="apbd-dci-icon">
									<span class="dashicons dashicons-admin-plugins"></span>
								</div>
								<div class="apbd-dci-desc">
									<h3>
										<?php esc_html_e( 'View Basic Plugin Info.', 'vitepos-lite' ); ?>
									</h3>
									<p>
										<?php esc_html_e( 'Current Plugin & SDK versions, and if active or uninstalled.', 'vitepos-lite' ); ?>
									</p>
								</div>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<?php
	}


}
