<?php
/**
 * Insights start file
 *
 * @package dci
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( ! function_exists( 'vtp_dci_dynamic_init' ) ) {
	/**
	 * The dci dynamic init is generated by appsbd
	 *
	 * @param mixed $params It is params param.
	 */
	function vtp_dci_dynamic_init( $params ) {

		if ( ! is_admin() ) {
			return;
		}

		$menu_slug    = isset( $params['menu']['slug'] ) ? $params['menu']['slug'] : false;
		$current_page = \Appsbd_Lite\V1\libs\AppInput::get_value( 'page', false );
		$text_domain  = isset( $params['text_domain'] ) && ! empty( $params['text_domain'] ) ? $params['text_domain'] : $params['slug'];

		/**
		 * For Attach SDK to current page
		 */
		$params['current_page'] = $current_page;
		$params['menu_slug']    = $menu_slug;
		$params['text_domain']  = $text_domain;

		/**
		 * Include SDK
		 */
		require_once __DIR__ . '/class-vtp-insights-sdk.php';
		if ( class_exists( 'Vtp_Insights_SDK' ) ) {
			new Vtp_Insights_SDK( $params );
		}
	}
}
