<?php
/**
 * Its payment method base.
 *
 * @since: 21/09/2021
 * @author: Sarwar Hasan
 * @version 1.0.0
 * @package VitePos\Libs
 */

namespace VitePos\Libs;

/**
 * Class Payment_Other_Method
 *
 * @package VitePos\Libs
 */
class Payment_Custom_Methods {
	public function __construct() {
		add_filter( 'vitepos/filter/payment/methods', array( $this, 'register_custom_payments' ) );
	}

	/**
	 * The register custom payments is generated by appsbd
	 *
	 * @param mixed $methods It is methods param.
	 *
	 * @return mixed
	 */
	public function register_custom_payments($methods){
		$cus_methods=self::get_custom_methods();
		foreach ( $cus_methods as $method ) {
			if(!empty($method->is_active) && $method->is_active=='Y') {
				$other2 = new Payment_Custom_Method();
				$other2->set_customization(  $method->id, $method->name,$method->icon, $method->flds );
				$methods[] = $other2;
			}
		}
		return $methods;
	}

	/**
	 * The get custom methods is generated by appsbd
	 *
	 * @return false|mixed
	 */
	public static function get_custom_methods(){
		return get_option('vtp_cus_methods',[]);
	}

	/**
	 * The update custom methods is generated by appsbd
	 *
	 * @param mixed $methods It is methods param.
	 *
	 * @return bool
	 */
	public static function update_custom_methods($methods) {
		return update_option('vtp_cus_methods',$methods);
	}
}
