<?php
/**
 * Its payment method base.
 *
 * @since: 21/09/2021
 * @author: Sarwar Hasan
 * @version 1.0.0
 * @package VitePos\Libs
 */

namespace VitePos\Libs;

/**
 * Class Payment_Other_Method
 *
 * @package VitePos\Libs
 */
class Payment_Custom_Method extends Payment_Method_Base {
	/**
	 * To initialize is generated by appsbd.
	 *
	 * @return mixed|void
	 */
	public function initialize() {
		$this->set_admin_name( 'custom' );
		$this->set_admin_viewable(false);
		$this->admin_data->is_enable = 'Y';
		$this->title = 'Custom';
		$this->icon  = 'vps vps-star-o';
		$this->id    = 'O';
		$this->comp  = 'basic';
	}

	/**
	 * The set customization is generated by appsbd
	 *
	 * @param mixed $admin_name It is admin_name param.
	 * @param mixed $id It is id param.
	 * @param mixed $title It is title param.
	 * @param mixed $icon It is icon param.
	 * @param mixed $is_note It is is_note param.
	 */
	public function set_customization($id,$title,$icon='',$fields=[],$comp='basic'){
		if(empty($icon)){
			$icon='vps vps-star-o';
		}
		$admin_name= sanitize_title_with_dashes($title);
		$this->set_admin_name( $admin_name );
		$this->admin_data->is_enable = 'Y';
		$this->title = $title;
		$this->icon  = $icon;
		$this->id    = $id;
		$this->comp  = $comp;
		if(!empty($fields)) {
			foreach ( $fields as $field ) {
				$field=(object)$field;
				$fld_id= sanitize_title_with_dashes($field->title);
				$is_show=!empty($field->is_show)?$field->is_show:'N';
				$this->add_field( $field->title, $fld_id,$field->is_req=='Y',$field->type,$is_show);
			}
			
		}
	}
	/**
	 * The set admin settings is generated by appsbd
	 *
	 * @return mixed|void
	 */
	public function set_admin_settings() {
		$this->set_admin_title_desc(
			'Enable Other Method',
			'It will allows to take payment using others method.'
		);
	}
}
